---
- hosts: host-servers
  remote_user: "{{ ansible_user }}"
  roles:
    - { role: common,               tags: [ 'common'  ] }
    - { role: kvm,               tags: [ 'kvm'  ] }
    - { role: terraform,               tags: [ 'terraform'  ] }
    - { role: terraform-libvirt-provider,               tags: [ 'terraform-libvirt-provider'  ] }
    - { role: terraform_apply,               tags: [ 'terraform_apply'  ] }