---
- name: download golang tar
  get_url:
    url: "{{ go_download_url }}"
    dest: /tmp/
    mode: 0440
  become: yes

- name: remove old installation of go
  file:
    path: /usr/local/go
    state: absent
  become: yes

- name: extract tarball
  unarchive:
    src: "/tmp/go{{go_version}}.linux-amd64.tar.gz"
    dest: /usr/local
    copy: no
  become: yes

- name: clone  terraform-provider-libvirt
  shell: /usr/local/go/bin/go get github.com/dmacvicar/terraform-provider-libvirt
  args:
    executable: /bin/bash

- name: install terraform-provider-libvirt
  shell: /usr/local/go/bin/go install github.com/dmacvicar/terraform-provider-libvirt
  args:
    executable: /bin/bash
  
- name: init terraform in the home dir
  shell:
    cmd: terraform init
    chdir: "{{remote_home_dir}}/"

- name: create plugin dir
  file:
    path: "{{ terraform_plugin_dir }}"
    state: directory

- name: copy libvirt plugin to terraform plugin dir
  copy:
    src: "{{ go_libvirt_plugin_dir }}"
    dest: "{{ terraform_plugin_dir }}"
    mode: a+x
    remote_src: yes
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: cleanup residue
  file: 
    path: "/tmp/go{{go_version}}.linux-amd64.tar.gz"
    state: absent
  become: yes