---
- name: Ensure required packages are available.
  package:
    name: 
      - unzip
    state: present

- name: "Download terraform {{ terraform_version }} binary."
  get_url:
    url: "{{ terraform_download_url }}"
    dest: /tmp/

- name: unarchive and move terraform binary to executable location
  unarchive:
    src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin/
    remote_src: yes
    
- name: change terraform file permissions
  file:
    path: /usr/local/bin/terraform
    mode: u+x
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    
- name: cleanup residue
  file:
    path: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
    state: absent